#!/bin/bash
# Modal LinkedIn Automation - Complete Deployment Script
# Run these commands in order to go live

echo "======================================================================"
echo "   MODAL LINKEDIN AUTOMATION - COMPLETE DEPLOYMENT"
echo "======================================================================"
echo ""
echo "Your Airtable Table ID: tbljg75KMQWDo2Hgu"
echo "Your Airtable Base ID: appw88uD6ZM0ckF8f"
echo ""

# Step 1: Deploy Modal App
echo ""
echo "STEP 1: Deploying Modal App to Production"
echo "======================================================================"
echo ""
echo "Run this command in your terminal:"
echo ""
echo "cd /Users/musacomma/Agentic\ Workflow/cloud"
echo "modal deploy modal_linkedin_automation.py"
echo ""
echo "⏳ This will take 2-3 minutes..."
echo "✅ SAVE THE MODAL URL when deployment completes (looks like: https://xxx--linkedin-automation.modal.run)"
echo ""

# Step 2: Create Modal Secrets
echo ""
echo "STEP 2: Create Modal Secrets (with your API keys)"
echo "======================================================================"
echo ""
echo "Run this command in your terminal:"
echo ""
echo "modal secret create linkedin-secrets \\"
echo "  AIRTABLE_API_KEY=patQCCzbAjKw675Bf.a9220198778415662363c84105e67b9c47399f5a01e27688f18f429115574a5c \\"
echo "  AIRTABLE_BASE_ID=appw88uD6ZM0ckF8f \\"
echo "  AIRTABLE_LINKEDIN_TABLE_ID=tbljg75KMQWDo2Hgu \\"
echo "  ANTHROPIC_API_KEY=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 \\"
echo "  REPLICATE_API_TOKEN=r8_TGbnWs9rFMEoddsvimJlUxRITKIuhio4JXdXF \\"
echo "  LINKEDIN_EMAIL=Musacbusiness@gmail.com \\"
echo "  LINKEDIN_PASSWORD=ziqmUn-pyvri7-rijbyg"
echo ""
echo "✅ Secret created successfully"
echo ""

# Step 3: Update Airtable Schema
echo ""
echo "STEP 3: Update Airtable Schema (MANUAL)"
echo "======================================================================"
echo ""
echo "In Airtable, update your 'Posts' table:"
echo ""
echo "A. Status Field - Add these select options:"
echo "   ☐ Draft"
echo "   ☐ Pending Review"
echo "   ☐ Approved - Ready to Schedule"
echo "   ☐ Scheduled"
echo "   ☐ Posted"
echo "   ☐ Rejected"
echo ""
echo "B. Add 6 new Date/Time fields (Column type: Date/Time):"
echo "   ☐ Image Generated At"
echo "   ☐ Scheduled Time"
echo "   ☐ Scheduled At"
echo "   ☐ Posted At"
echo "   ☐ Scheduled Deletion Date"
echo "   ☐ Rejected At"
echo ""

# Step 4: Create Airtable Automations
echo ""
echo "STEP 4: Create 3 Airtable Automations (MANUAL)"
echo "======================================================================"
echo ""
echo "⚠️  Replace [YOUR-MODAL-URL] with the URL from Step 1"
echo ""

echo "AUTOMATION 1: Generate Images"
echo "────────────────────────────"
echo "Trigger: When Status is 'Pending Review'"
echo "Action: Webhook"
echo "  Method: POST"
echo "  URL: https://[YOUR-MODAL-URL]/webhook/status-change"
echo "  Body:"
echo "  {"
echo "    \"record_id\": \"{record_id}\","
echo "    \"status\": \"Pending Review\","
echo "    \"base_id\": \"{base_id}\","
echo "    \"table_id\": \"{table_id}\""
echo "  }"
echo "Status: Turn ON ✓"
echo ""

echo "AUTOMATION 2: Schedule Posts"
echo "────────────────────────────"
echo "Trigger: When Status is 'Approved - Ready to Schedule'"
echo "Action: Webhook"
echo "  Method: POST"
echo "  URL: https://[YOUR-MODAL-URL]/webhook/status-change"
echo "  Body:"
echo "  {"
echo "    \"record_id\": \"{record_id}\","
echo "    \"status\": \"Approved - Ready to Schedule\","
echo "    \"base_id\": \"{base_id}\","
echo "    \"table_id\": \"{table_id}\""
echo "  }"
echo "Status: Turn ON ✓"
echo ""

echo "AUTOMATION 3: Handle Rejections"
echo "──────────────────────────────"
echo "Trigger: When Status is 'Rejected'"
echo "Action: Webhook"
echo "  Method: POST"
echo "  URL: https://[YOUR-MODAL-URL]/webhook/status-change"
echo "  Body:"
echo "  {"
echo "    \"record_id\": \"{record_id}\","
echo "    \"status\": \"Rejected\","
echo "    \"base_id\": \"{base_id}\","
echo "    \"table_id\": \"{table_id}\""
echo "  }"
echo "Status: Turn ON ✓"
echo ""

# Step 5: Test
echo ""
echo "STEP 5: Test All 3 Workflows"
echo "======================================================================"
echo ""
echo "TEST 1: Image Generation"
echo "  1. Create a test post in Airtable (Draft status)"
echo "  2. Change status to 'Pending Review'"
echo "  3. Wait 30-60 seconds"
echo "  4. ✅ Image URL should appear"
echo ""
echo "TEST 2: Auto-Scheduling"
echo "  1. Change test post status to 'Approved - Ready to Schedule'"
echo "  2. Wait 5 seconds"
echo "  3. ✅ Status should change to 'Scheduled'"
echo "  4. ✅ 'Scheduled Time' field should be populated"
echo ""
echo "TEST 3: Rejection"
echo "  1. Create another test post (Draft)"
echo "  2. Change status to 'Rejected'"
echo "  3. ✅ 'Scheduled Deletion Date' should appear (24h from now)"
echo ""

# Summary
echo ""
echo "======================================================================"
echo "   🎉 GO-LIVE CHECKLIST"
echo "======================================================================"
echo ""
echo "☐ Step 1: Deploy Modal app"
echo "☐ Step 2: Create Modal secrets"
echo "☐ Step 3: Update Airtable schema"
echo "☐ Step 4: Create 3 Airtable Automations"
echo "☐ Step 5: Test all 3 workflows"
echo ""
echo "Once all complete: You're LIVE! 🚀"
echo ""
echo "======================================================================"
